export const students = [
  { id: 1, name: 'Leon' },
  { id: 2, name: 'Emilia' },
  { id: 3, name: 'Jonas' },
  { id: 4, name: 'Hannah' },
  { id: 5, name: 'Elias' },
  { id: 6, name: 'Lina' },
  { id: 7, name: 'Paul' },
  { id: 8, name: 'Clara' },
  { id: 9, name: 'Maximilian' },
  { id: 10, name: 'Sophie' },
  { id: 11, name: 'Noah' },
  { id: 12, name: 'Marie' },
  { id: 13, name: 'Lukas' },
  { id: 14, name: 'Johanna' },
  { id: 15, name: 'Tim' },
  { id: 16, name: 'Amelie' },
  { id: 17, name: 'Felix' },
  { id: 18, name: 'Lea' },
  { id: 19, name: 'David' },
  { id: 20, name: 'Laura' },
];
